### ISSUE TITLE
HTTPS with self-signed certs: missing env var?

### ISSUE THREAD

**Issue by teutat3s** [LOQ9/drone-nomad#2]
Thank you for this nice plugin!

In the Nomad documentation some important CLI environment variables are declared, e.g.
for the Nomad Token or TLS settings.
I see that the token is already implemented.
What about `NOMAD_CACERT` `NOMAD_CLIENT_CERT` `NOMAD_CLIENT_KEY`?
Especially the first would be very helpful for using HTTPS and verifying self-signed certs.

Are these env vars for TLS also available in this plugin, because I can't see them in the code.
Comparing this plugin's `main.go` to `drone/drone-vault`'s I can see that the vault equivalent env vars are declared explicitly in that plugin.

Would this be something that still needs implementation? 
Another question is what would be the best way to add a self-signed `ca.crt` to `drone-nomad`...
Is host-volume the only option?

**Comment by marcotuna** [comment]
Hi, thanks for reporting this. I will try to check this in the following hours/days!

**Comment by teutat3s** [comment]
Thank you very much!

To give a first answer to the last question: 
For `drone/drone-vault` I just did a lazy
```
docker run -v /home/ubuntu/ca.crt:/ca.crt -e VAULT_CACERT=/ca.crt [...] drone/drone-vault
```
...and it works. A similar host-volume would have to be configured in every `.drone.yml` for `drone-nomad`.
But host-volumes are not the most secure way - so maybe there's a better solution.

**Comment by teutat3s** [comment]
Just did a quick deployment test with our small nomad cluster.

This works already, with a trusted repo and e.g. this `.drone.yml`:

```text
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

- name: deploy
  image: loq9/drone-nomad
  volumes:
  - name: ssl
    path: /ssl/ca.crt
  environment:
    NOMAD_CACERT: /ssl/ca.crt
  settings:
    addr: https://nomad.service.consul:4646
    template: example-docker.nomad
    token:
      from_secret: nomad_token


volumes:
- name: ssl
  host:
    path: /home/ubuntu/ca.crt

---
kind: secret
name: nomad_token
get:
  path: secret/data/drone/nomad
  name: token

```

**Comment by marcotuna** [comment]
Hello @teutat3s 
I added support for this on PR #3, there are some more information there.
Can you please check with the following settings?

```
...
- name: deploy
  image: loq9/drone-nomad
  settings:
    addr: https://nomad.service.consul:4646
    template: example-docker.nomad
    token:
      from_secret: nomad_token
    tls_client_cert_pem:
      from_secret: nomad_tls_client_cert_pem
    tls_client_key_pem:
      from_secret: nomad_tls_client_key_pem
...
```

Be aware that the docker image from this repo is tagged with the :latest tag, if you have that image cached in your servers it is better if you manually remove them `docker rmi loq9/drone-nomad:latest`. If this project continues to grow I will probably consider starting versioning.

I will the looking for further feedback from you
