### ISSUE TITLE
Custom Env Vars

### ISSUE THREAD

**Issue by microadam** [LOQ9/drone-nomad#8]
Hello,

I have some custom environment variables that I would like to replace in my template, which aren't one of the supported DRONE_xxx vars. Is it possible to use these custom ones? Or do ALL possible tokens that can be replaced have to be baked into the plugin?

**Comment by xeroc** [comment]
I want to know this too

**Comment by xeroc** [comment]
[Use case](https://www.nomadproject.io/docs/job-specification/hcl2/variables):

In nomad:
```
variable "deploy_key" {
type = string
default = ""
}

job "somejob" {
...
      artifact {
        source      = "git::ssh://git@gitea-ssh.consul.service/some/repo"
        destination = "local/repo"
        options {
          sshkey = "${base64encode(var.deploy_key)}"
          depth = 1
        }
      }
...
}
```

Cannot get this to work with any combination of environment variables I came up with including the way I read the docs:

```
---
kind: pipeline
name: default
type: docker

steps:
  - name: deploy
    image: loq9/drone-nomad:latest
    environment:
      NOMAD_VAR_deploy_key:
        from_secret: DEPLOY_KEY
    settings:
      addr: https://nomad.infra.chainsquad.com
      template: .nomad.hcl
      token:
        from_secret: NOMAD_TOKEN
    when:
      event:
        - push
```
